<?php 
return array (
  'site_name' => '微学宝',
  'site_url' => 'http://www.vxuebao.com',
  'site_title' => '微学宝-e-learning及移动学习微课制作工具|e-learning及移动学习、elearning平台、企业学习平台、企业网络学习平台微课制作工具领导品牌|助你轻松创建企业培训学习平台微课|众多企业在线学习平台微课之选',
  'keyword' => '微学宝,微课,微课制作工具,企业培训微课,微课制作软件,微课模板,微课制作技巧,微课制作方法,微课制作大全,e-learning,移动学习,微课课程,微课学习,微课培训,e-learning及移动学习课程,企业学习平台,网络学习平台,elaerning平台',
  'content' => '微学宝-e-learning及移动学习微课制作工具，是一个企业网络学习快课件制作平台，帮助企业快速创建e-learning及移动学习微课。微学宝突破多年来企业自主开发e-learning及移动学习课程上的难点，内含大量微课模板，企业在平台上通过“傻瓜式”操作，即可快速创建e-learning及移动学习微课，丰富其e-learning及移动学习、在线学习平台。微学宝功能强大，支持图片、文字、背景音乐、音频、视频、链接、动画、样式设计等功能，满足企业e-learning及移动学习微课的创意发挥需求，提高企业elearning及移动学习平台的使用。',
  'web_muban_status' => '3',
  'js_local_or_remote' => 'local',
  'is_open_reg' => '1',
  'is_user_anli_shenghe' => '0',
  'reg_validdays' => '9000',
  'allow_nums' => '9000000',
  'xd' => '0',
  'lastpagetext' => '微学宝',
  'lastpagetext_color' => '#23a3d3',
  'lastpagelink' => 'http://www.vxuebao.com',
  'jubao_link' => 'http://www.vxuebao.com/',
  'guding_qi_xd' => '15',
  'custome_qi_xd' => '30',
  'qi_ad_xds' => '99',
  'loadingLogo_qi_xd' => '100',
  'ipc' => '粤ICP备13053614号-4',
  'countCode' => '',
);